// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trnmzcugbigbldgpnzbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRybm16Y3VnYmlnYmxkZ3BuemJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzQ2NTgsImV4cCI6MjA2MTExMDY1OH0.F6JfjZspTvURoMzRLdhohuHUyBSv3J2lH-PQ2dgrjv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);